FROM node:13

ENV NODE_ENV=development

WORKDIR /usr/src/app2

RUN npm install
RUN npm install express
RUN npm install express-generator
RUN npm install nodemon -g
RUN npm install morgan
RUN npm install body-parser
RUN npm install ejs
RUN npm install connect method-override
RUN npm install cookie-parser express-session csurf
RUN npm install twitter
RUN npm install fs

EXPOSE 3000